//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.4-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BotsScript.g4 by ANTLR 4.5.4-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBotsScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.4-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class BotsScriptBaseListener : IBotsScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] BotsScriptParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] BotsScriptParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] BotsScriptParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] BotsScriptParser.StmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.botToDest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBotToDest([NotNull] BotsScriptParser.BotToDestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.botToDest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBotToDest([NotNull] BotsScriptParser.BotToDestContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.valueToBot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueToBot([NotNull] BotsScriptParser.ValueToBotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.valueToBot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueToBot([NotNull] BotsScriptParser.ValueToBotContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] BotsScriptParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] BotsScriptParser.ValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.bot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBot([NotNull] BotsScriptParser.BotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.bot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBot([NotNull] BotsScriptParser.BotContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.dest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDest([NotNull] BotsScriptParser.DestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.dest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDest([NotNull] BotsScriptParser.DestContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput([NotNull] BotsScriptParser.OutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput([NotNull] BotsScriptParser.OutputContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
