//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.4-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BotsScript.g4 by ANTLR 4.5.4-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BotsScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.4-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface IBotsScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] BotsScriptParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] BotsScriptParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] BotsScriptParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] BotsScriptParser.StmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.botToDest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBotToDest([NotNull] BotsScriptParser.BotToDestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.botToDest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBotToDest([NotNull] BotsScriptParser.BotToDestContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.valueToBot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueToBot([NotNull] BotsScriptParser.ValueToBotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.valueToBot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueToBot([NotNull] BotsScriptParser.ValueToBotContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] BotsScriptParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] BotsScriptParser.ValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.bot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBot([NotNull] BotsScriptParser.BotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.bot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBot([NotNull] BotsScriptParser.BotContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.dest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDest([NotNull] BotsScriptParser.DestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.dest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDest([NotNull] BotsScriptParser.DestContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="BotsScriptParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput([NotNull] BotsScriptParser.OutputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BotsScriptParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput([NotNull] BotsScriptParser.OutputContext context);
}
